(function(plt) {
plt.T_DATA = {
  HOSTING_STATUS : Symbol(),
  ADDON_SCRIPT : Symbol(),
  SERVICE_QUEUE_SIZE : Symbol(),
  BLOG_CONFIG : Symbol(),
  WORKSHOP_CONFIG : Symbol(),
  SHOP_CONFIG : Symbol(),
  SHOP_ADDRESS_LABELS : Symbol(),
  SHOP_BRANCH_LABELS : Symbol(),
  SHOP_BRANCH : Symbol(),
  SHOP_REGISTER : Symbol(),
  PAYMENT_TERMINAL : Symbol(),
  GLOBAL_COMMMUNITY_PROFILE : Symbol(),
  COMMUNITY_PROFILE : Symbol(),
  MENUS : Symbol(),
  GROUPS : Symbol(),
  HASHTAGS : Symbol(),
  MESSAGES : Symbol(),
  CURRENCIES : Symbol(),
  ASSET : Symbol(),
  SOCIAL_INFO : Symbol(),
  USER_PROFILE : Symbol(),
  USER_PUBLIC_PROFILES : Symbol(),
  USER_INBOX_SIGNAL : Symbol(),
  USER_ADDRESS_IDS : Symbol(),
  WEB3_USER_PROFILE : Symbol(),
  WEB3_USER_IDOLS : Symbol(),
  DRAFT_ORDERS : Symbol(),
  ADDRESS : Symbol(),
  JOURNAL : Symbol(),
  DRAFT_ARTICLE : Symbol(),
  POST : Symbol(),
  NEW_OWNER_POST : Symbol(),
  DRAFT_ARTICLE_IDS : Symbol(),
  POST_IDS : Symbol(), // Unclear signal, currently only happens when dba.Blog
                       // data reset
  QUIZ : Symbol(),
  QUIZ_IDS : Symbol(),
  EMAIL : Symbol(),
  EMAIL_IDS : Symbol(),
  PROJECT : Symbol(),
  PRODUCT : Symbol(),
  PROPOSAL : Symbol(),
  VOTE : Symbol(),
  SUPPLIER_ORDER : Symbol(),
  CUSTOMER_ORDER : Symbol(),
  OGP : Symbol(),
  LOGIN_RESULT : Symbol(),
  WALKIN_QUEUE_ITEMS : Symbol(),
  WALKIN_QUEUE_ITEM : Symbol(),
  KEY_UPDATE : Symbol(),
};

plt.T_ACTION = {
  LOGIN : Symbol(),
  ACCOUNT_UPGRADE : Symbol(),
  LOGIN_SUCCESS : Symbol(),
  PROXY_LOGIN_SUCCESS : Symbol(),
  SHOW_BLOG_ROLES : Symbol(),
  SHOW_USER_INFO : Symbol(),
  SHOW_GROUP_INFO : Symbol(),
};
}(window.plt = window.plt || {}));
